### ISSUE TITLE
DefaultInternalMethod [[GetOwnProperty]] cannot be used for Window

### ISSUE THREAD

**Issue by domenic** [annevk/html-cross-origin-objects#32]
Window objects have exotic [[GetOwnProperty]] etc., as specified in http://heycam.github.io/webidl/#getownproperty. So you need to call W.[[GetOwnProperty]], not DefaultInternalMethod([[GetOwnProperty]], W).

Location objects also have exotic [[GetOwnProperty]] etc. since they are platform objects, but I think it is fine to overwrite that, because they always fall back to the default anyway.

I think the best way to solve this will be to avoid reusing code between the two objects :-/.

**Comment by annevk** [comment]
Actually I think the only magic for `Window` happens to be the indexed getters (since it's a global the named properties live somewhere else) and @bzbarsky has proposed moving the indexed getters to `WindowProxy`.

Having said that, due to cross-origin objects needing to behave as if all the properties are own properties, there is a ton of things that need to change here somehow.

**Comment by domenic** [comment]
Well, [Global] objects already behave as if all their properties are own properties, sort of. I guess there's still the global scope polluter and EventTarget and such in the prototype chain.

**Comment by annevk** [comment]
We can avoid using the exotic [[GetOwnProperty]] defined in IDL by defining the indexed getters directly on the WindowProxy object for both same-origin and cross-origin. bz already indicated that he would prefer that solution. That way Window doesn't need indexed getters anymore and no longer needs to be exotic.

The only thing we will need to do then for the cross-origin case is to also expose the named properties as own properties (since they normally are on the named properties object which will be hidden). This will obsolete https://github.com/whatwg/html/pull/544 too in the process. The easiest way to do that seems to simply define what their function would do here.

Hopefully I can write something up for that today.

Also, even if parts of GetOwnProperty cannot be reused, that doesn't mean DefaultInternalMethod in general is bad, right? (I'm trying to replace that by the way by patching ecma262, see https://github.com/tc39/ecma262/pull/356 and https://github.com/tc39/ecma262/pull/357, so we can invoke Ordinary\* abstract operations everywhere.)

**Comment by domenic** [comment]
Don't you also need to handle EventTarget?

> Also, even if parts of GetOwnProperty cannot be reused, that doesn't mean DefaultInternalMethod in general is bad, right?

I think it's kind of bad when used on Window. In general a proxy should delegate to its target, not use a different set of internal methods applied to the target.

**Comment by annevk** [comment]
@domenic to support named properties on Window objects for the cross-origin case. Would you prefer that I simply create a branch in CrossOriginGetOwnProperty based on whether _O_ is a Window object or should I remove step 4 from CrossOriginGetOwnProperty, have Window and Location invoke what remains of that algorithm in their [[GetOwnProperty]] algorithm, and basically use the return value?

**Comment by annevk** [comment]
No, `EventTarget` basically doesn't apply in the cross-origin case.

**Comment by annevk** [comment]
I don't understand why it's bad in general for Window. How is DefaultInternalMethod coupled with GetPrototypeOf bad?

**Comment by domenic** [comment]
In general I think CrossOriginGetOwnProperty should probably be removed in favor of explicit different algorithms for each of the two objects.

> No, EventTarget basically doesn't apply in the cross-origin case.

So the properties should show up as undefined? That's nice and easy, if it's web-compatible.

> I don't understand why it's bad in general for Window. How is DefaultInternalMethod coupled with GetPrototypeOf bad?

It's a general argument about polymorphic method dispatch being preferred to explicitly choosing a specific method and then applying it to an object. In JS terms, you're essentially proposing:

``` js
const m = OrdinaryObject.getOwnProperty;
return m.call(proxyTarget, ...);
```

instead of the more natural

``` js
return proxyTarget.getOwnProperty(...);
```

In this particular case, the results will be equal, but only because of some external factors like Window not having any named or indexed properties, and not getting any other exotic behaviors defined (either via IDL or elsewhere). That kind of coupling to special facts about Window, which might change over time as we update the spec, is fragile and not good development practice IMO. And I just don't see the benefit.

**Comment by annevk** [comment]
I think the benefit of tightly coupling Window and Location is pretty big, since implementers want them to behave the same.

**Comment by annevk** [comment]
And in particular I don't see the benefit at all of duplicating all the logic of CrossOriginGetOwnProperty. Almost everything would end up being identical.

**Comment by domenic** [comment]
I disagree. They are very different types of objects: WindowProxy is a proxy around another mostly-ordinary object, whereas Location is a super-exotic object all on its own. If implementers want them to behave the same, then this spec is just off-base and needs a new model.

**Comment by annevk** [comment]
I don't know how to act on that feedback.

**Comment by domenic** [comment]
From discussion in IRC: my suggestion is that the "If IsWindowOrLocationSameOrigin(O), then return DefaultInternalMethod([[X]], O)" step inside the CrossOriginX(...) abstract operations get moved out, since it should behave differently for WindowProxy (where it delegates, like a proxy) and Location (where it falls back to ordinary object behavior).

So for example:

### Window [[OwnPropertyKeys]] ( )
1. Let W be this.[[Window]].
2. If IsWindowOrLocationSameOrigin(W), then return W.[[OwnPropertyKeys]]().
3. Return CrossOriginOwnPropertyKeys(W).

### Location [[OwnPropertyKeys]] ( )
1. If IsWindowOrLocationSameOrigin(this), then return DefaultInternalMethod([[OwnPropertyKeys]], this).
2. Return CrossOriginOwnPropertyKeys(this).

### CrossOriginOwnPropertyKeys ( O )
1. Let keys be a new empty List.
2. Repeat for each e that is an element of CrossOriginProperties(O):
   1. Add e.[[property]] as the last element of keys.
3. Return keys.

This has the added benefit of the CrossOriginX()s actually doing what their name says, and operating in the cross origin case.

**Comment by bzbarsky** [comment]
> So the properties should show up as undefined?

No, they should throw.  Seriously, test actual browser behavior.  Anything you try to do with a cross-origin window outside a pretty small whitelist of stuff throws.

Frankly, the way I think we should do Window is to have it be a completely normal object in all ways.  Any magic should go into WindowProxy.  In particular, in the cross-origin case WindowProxy can look up the named properties itself.  This is particularly desirable, imo, because the set of names that cross-origin WindowProxy exposes is not at all the same as the set of names exposed on the Windows named properties object: it's a strict subset that excludes a whole bunch of stuff.

**Comment by domenic** [comment]
Sure, I noticed that typo but didn't correct it; apologies. As for testing, I'm mostly just here to provide consulting advice on writing ES-style specs, not to work out the behavior.

**Comment by annevk** [comment]
@domenic your approach would still require refactoring of the CrossOriginGetOwnPropertyHelper abstract operation in a way that will make it less clear that it's actually the same code. Is there a different way to invoke the forwarding operation so "DefaultInternalMethod" or something similar could just do the right thing for both Location and window proxy?

**Comment by annevk** [comment]
Tentative resolution here is to simply suck this up and make it clear we depend on Window being ordinary.
